# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]

jobs:
  semver:
    name: increment and publish git tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
